name: Publish to registry

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  prepare:
    name: Calculate next version
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.SemVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.3
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.3
        with:
          useConfigFile: true

  infra:
    name: Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            infrastructure

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TRICEP_CLIENT_ID }}
          tenant-id: ${{ secrets.TRICEP_TENANT_ID }}
          subscription-id: ${{ secrets.TRICEP_SUBSCRIPTION_ID }}

      - name: Deploy bicep
        uses: Azure/cli@v2
        with:
          azcliversion: 2.66.0
          inlineScript: |
            az deployment sub create \
              --location westeurope \
              --template-file infrastructure/main.bicep \
              --parameters infrastructure/params/main.prd.bicepparam \

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ prepare, infra ]
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src
      
      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TRICEP_CLIENT_ID }}
          tenant-id: ${{ secrets.TRICEP_TENANT_ID }}
          subscription-id: ${{ secrets.TRICEP_SUBSCRIPTION_ID }}

      - name: Publish Bicep module
        uses: azure/cli@v1
        with:
          inlineScript: |
            for x in ls -al src; do
              echo "$x"
            done

            # az bicep publish \
            #   --file src/main.bicep \
            #   --target 'br:toycompany.azurecr.io/main:${{needs.prepare.outputs.semver}}'
